Add Greg and Sebastian as Editors.
w3c/vc-data-integrity pull request #113
Opened 2023-07-09 20:51 UTC by msporny

This PR adds Greg and Sebastian as Editors. The PR shouldn't be processed until after Sebastian's IE application has been processed.

2023-07-09 20:57 UTC, msporny commented on index.html
> +            company: "Invited Expert", w3cid: 0
@Wind4Greg, I need you to fill out your w3cid here. You can find out what it is by going here: 

https://www.w3.org/users/myprofile/

The URL will change into something that looks like this:

https://www.w3.org/users/41758/

Whatever number shows up in the URL is your w3cid.

2023-07-09 20:57 UTC, msporny commented on index.html
> +            company: "Invited Expert", w3cid: 0
@seabass-labrax, I need you to fill out your w3cid here. You can find out what it is by going here: 

https://www.w3.org/users/myprofile/

The URL will change into something that looks like this:

https://www.w3.org/users/41758/

Whatever number shows up in the URL is your w3cid.

2023-07-09 21:16 UTC, dlongley approved these changes

2023-07-10 15:47 UTC, Wind4Greg commented on index.html
> +            company: "Invited Expert", w3cid: 0
```suggestion
            company: "Invited Expert", w3cid: 140479
```

2023-07-10 15:48 UTC, Wind4Greg approved these changes

2023-07-11 08:55 UTC, iherman commented
As mentioned [elsewhere](https://github.com/w3c/vc-di-eddsa/pull/50#issuecomment-1628305781) we should receive a formal IE application from @seabass-labrax. As said in the PR description, this PR _MUST NOT_ be merged until that is settled.

2023-07-11 10:09 UTC, seabass-labrax requested changes

2023-07-11 10:09 UTC, seabass-labrax commented on index.html
> +            company: "Invited Expert", w3cid: 0
```suggestion
            company: "Invited Expert", w3cid: 140132
```

2023-07-21 13:05 UTC, msporny commented
Editorial, multiple reviews, @seabass-labrax and @Wind4Greg are now WG members, no objections, merging.

2023-07-21 13:05 UTC, merged