Add guidance to recommend usage of DataIntegrityProof pattern.
w3c/vc-data-integrity pull request #117
Opened 2023-07-15 21:29 UTC by msporny

This PR is an attempt to address issue #84 by adding guidance to cryptographic suite authors such that they follow the new `DataIntegrityProof` pattern.

@silverpill, please let me know if this addresses the concerns you raised in #84. Also note that we have added a header that cross-links all modern cryptosuite specifications here:

https://w3c.github.io/vc-data-integrity/

![image](https://github.com/w3c/vc-data-integrity/assets/108611/6f2fc9d9-aebe-45e3-88d8-998eb424d6bf)

2023-07-16 08:44 UTC, iherman approved these changes
Not _necessary_ for merging this PR, but it may still be a good idea to sync this with an update of [spec-dir proof table](https://w3c.github.io/vc-specs-dir/#proof). The latter seems to be outdated with regard to the references listed in the header of this document...

2023-07-16 13:26 UTC, silverpill approved these changes
I think the "Related Specifications" list and this PR together address all concerns raised in issue #84

Thank you!

2023-07-16 14:20 UTC, msporny commented
> Not _necessary_ for merging this PR, but it may still be a good idea to sync this with an update of [spec-dir proof table](https://w3c.github.io/vc-specs-dir/#proof). The latter seems to be outdated with regard to the references listed in the header of this document...

Done in https://github.com/w3c/vc-specs-dir/pull/26

2023-07-16 15:00 UTC, martyr280 approved these changes

2023-07-16 17:01 UTC, dlongley approved these changes
Thanks! A couple of suggestions.

2023-07-16 17:01 UTC, dlongley commented on index.html
> +described in this section.
The *need* for a proliferation of *contexts* (which is an implementation burden when it's not providing significant benefits) was the real problem, I think, so I've changed this a bit:

```suggestion
led to a greater burden for cryptographic suite implementation, where every new
cryptographic suite would require a new JSON-LD Context to be specified,
resulting in a less-than-ideal developer experience. The design pattern was
changed in 2020 to streamline the approach such that a developer would only need
to include a single JSON-LD Context to support all modern cryptographic suites.
As a result, more modern cryptosuites such as the EdDSA Cryptosuites
[[?DI-EDDSA]] and the ECDSA Cryptosuites [[?DI-ECDSA]] utilize the pattern
described in this section.
```

2023-07-16 17:01 UTC, dlongley commented on index.html
> +Verifiable Credentials Specifications Directory</a>.
Additionally, cryptosuites should encapsulate specific cryptographic data within `proofValue` to avoid the need for additional contexts and avoid direct exposure of cryptographic details to the application layer, which allows applications to have simpler (and less frequently changing) schemas and fewer validation / potential security mistakes around that data.

```suggestion
the modern pattern where the `type` is set to `DataIntegrityProof`, the
`cryptosuite` property carries the identifier for the cryptosuite, and any
cryptosuite-specific cryptographic data is encapsulated (not directly
exposed as application layer data) within `proofValue`. A list of known
cryptographic suite specifications is provided in the
<a href="https://w3c.github.io/vc-specs-dir/#proof">Proof types section of the
Verifiable Credentials Specifications Directory</a>.
```

2023-07-17 13:19 UTC, TallTed requested changes
Lightly massaged...

2023-07-17 13:19 UTC, TallTed commented on index.html
> +cryptographic suite. For example, the
```suggestion
        <p class="note" title="Design Patterns of Legacy Cryptographic Suites">
One of the design patterns seen in Data Integrity cryptosuites from
2012 to 2020 was use of the `type` property to establish a specific type for a
cryptographic suite. For example, the
```

2023-07-17 13:19 UTC, TallTed commented on index.html
> +Verifiable Credentials Specifications Directory</a>.
Again, this is based on @dlongley's tweaked content.
```suggestion
To improve the developer experience, authors creating new Data Integrity
cryptographic suite specifications SHOULD use the modern pattern &mdash; where
the `type` is set to `DataIntegrityProof`; the `cryptosuite` property carries
the identifier for the cryptosuite; and any cryptosuite-specific cryptographic
data is encapsulated (i.e., not directly exposed as application layer data)
within `proofValue`. A list of cryptographic suite specifications that are
known to follow this pattern is provided in the
<a href="https://w3c.github.io/vc-specs-dir/#proof">Proof types section of
the Verifiable Credentials Specifications Directory</a>.
```
If the last sentence is inaccurate as edited, then both the list and the sentence need further editing, to provide guidance as to which of the listed suites follow the older pattern, and which the newer.

2023-07-17 13:19 UTC, TallTed commented on index.html
> +described in this section.
Based on @dlongley's tweaks
```suggestion
led to a greater burden on cryptographic suite implementations, where every new
cryptographic suite required a new JSON-LD Context to be specified, resulting
in a sub-optimal developer experience. A streamlined version of this design
pattern emerged in 2020, such that a developer would only need to include a
single JSON-LD Context to support all modern cryptographic suites. This
encouraged more modern cryptosuites &mdash; such as the EdDSA Cryptosuites
[[?DI-EDDSA]] and the ECDSA Cryptosuites [[?DI-ECDSA]] &mdash; to be built 
based on the streamlined pattern described in this section.
```

2023-07-17 14:41 UTC, Wind4Greg approved these changes
Good, helpful, clarifying text.

2023-07-21 13:15 UTC, msporny commented on index.html
> +To improve the developer experience, authors creating new Data Integrity
```suggestion
based on the streamlined pattern described in this section.
        <br><br>
To improve the developer experience, authors creating new Data Integrity
```

2023-07-28 20:56 UTC, msporny commented on index.html
> +Verifiable Credentials Specifications Directory</a>.
Merged @TallTed's suggestions, which built on your suggestions.

2023-07-28 20:56 UTC, merged