Clarify verificationMethod for controller document
w3c/vc-data-integrity pull request #123
Opened 2023-07-18 18:39 UTC by Wind4Greg

This PR addresses issue https://github.com/w3c/vc-data-integrity/issues/108 and adds a clarifying note to the *controller documents* section.

2023-07-18 18:50 UTC, dlongley approved these changes

2023-07-19 13:35 UTC, TallTed requested changes

2023-07-19 13:35 UTC, TallTed commented on index.html
> +documents, is REQUIRED. See section <a href="#proofs"></a>.
```suggestion
The `verificationMethod` property is REQUIRED for proofs, unlike controller 
documents, for which it is optional. See section <a href="#proofs"></a>.
```

2023-07-23 15:39 UTC, msporny approved these changes

2023-07-28 21:27 UTC, merged