Add requirement for protection of terms
w3c/vc-data-integrity pull request #125
Opened 2023-07-19 18:43 UTC by Wind4Greg

This PR addresses issue https://github.com/w3c/vc-data-integrity/issues/48 to add a requirement for protecting *terms* in cryptosuite definitions. In particular to use the `@protected` keyword to protect against redefinition of terms in JSON-LD *contexts*.

Note that this issue was assigned to me, but I'm not a JSON-LD expert. Feel free to modify text to increase precision or better reflect the intent of the issue.

2023-07-19 20:13 UTC, dlongley approved these changes

2023-07-23 15:44 UTC, msporny approved these changes

2023-07-24 10:01 UTC, iherman approved these changes

2023-07-24 21:55 UTC, TallTed requested changes
Hopefully this makes it read less like the unsafe redefinition uses `@protected`.

2023-07-24 21:55 UTC, TallTed commented on index.html
> +protected from unsafe redefinition using the <code>@protected</code> keyword.
```suggestion
protected from unsafe redefinition, by use of the <code>@protected</code> keyword.
```

2023-07-28 21:41 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-07-28 21:41 UTC, merged