Require cryptosuite specifications to mitigate against poison graphs.
w3c/vc-data-integrity pull request #128
Opened 2023-07-24 00:57 UTC by msporny

This PR attempts to address issue #87 by 1) documenting that some transformations (like RDF Dataset Canonicalization) can be attacked, and 2) that there are mitigations for those attacks and cryptosuite specifications MUST ensure that those mitigations are implemented.

2023-07-24 17:06 UTC, dlongley approved these changes

2023-07-24 17:51 UTC, Wind4Greg approved these changes

2023-07-24 22:23 UTC, TallTed requested changes

2023-07-24 22:23 UTC, TallTed commented on index.html
> +excessive processing cycles. These class of attacks are called
```suggestion
excessive processing cycles. This class of attack is called
```

2023-07-24 22:23 UTC, TallTed commented on index.html
> +<a data-cite="RDF-CANON#dataset-poisoning">dataset poisoning</a> and all modern
```suggestion
<a data-cite="RDF-CANON#dataset-poisoning">dataset poisoning</a>, and all modern
```

2023-07-24 22:23 UTC, TallTed commented on index.html
> +halt processing. The test suites for RDF Dataset Canonicalization contains such
```suggestion
halt processing. The test suites for RDF Dataset Canonicalization includes such
```

2023-07-24 22:23 UTC, TallTed commented on index.html
> +utilize transformations are required to mitigate these sorts of attacks and
```suggestion
use transformations are required to mitigate these sorts of attacks, and
```

2023-07-28 14:12 UTC, dmitrizagidulin approved these changes
:+1: (once TallTed's changes are applied)

2023-07-29 18:09 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-07-29 18:09 UTC, merged