Define anchors for secretKeyJwk and secretKeyMultibase
w3c/vc-data-integrity pull request #152
Opened 2023-08-06 16:14 UTC by msporny

This PR addresses issue #151 by refactoring the verification material sections and adding anchors for secretKeyJwk and secretKeyMultibase.

2023-08-06 17:19 UTC, dmitrizagidulin commented on index.html
> +any members of the private information class, such as "d", as described
```suggestion
include any members of the private information class, such as "d", as described
```

2023-08-06 17:20 UTC, dmitrizagidulin approved these changes
👍

2023-08-06 17:43 UTC, Wind4Greg approved these changes

2023-08-06 19:40 UTC, dlongley approved these changes

2023-08-06 19:40 UTC, dlongley commented on index.html
> +of verification material include `JsonWebKey` and `Multikey`.
```suggestion
of verification methods include `JsonWebKey` and `Multikey`.
```

2023-08-06 19:40 UTC, dlongley commented on index.html
> +The `type` property MUST contain the string `Multikey`.
```suggestion
The value of the `type` property MUST contain the string `Multikey`.
```

2023-08-06 19:40 UTC, dlongley commented on index.html
> +The `type` property MUST contain the string `JsonWebKey`.
```suggestion
The value of the `type` property MUST contain the string `JsonWebKey`.
```

2023-08-07 04:40 UTC, iherman approved these changes
Just a note for myself: once this is merged, I will have to check whether all these terms are part of the vocabulary, too. I must admit I am lost in the maze of PR-s and I do not remember which one is already there via one of those, and which one is missing...

2023-08-07 20:01 UTC, TallTed requested changes
A few editorial tweaks.

2023-08-07 20:01 UTC, TallTed commented on index.html
> +method</a> types please see the [[?SECURITY-VOCABULARY]].
```suggestion
method</a> types, please see the [[?SECURITY-VOCABULARY]].
```

2023-08-07 20:01 UTC, TallTed commented on index.html
>  and supporting formats that have historically had broad deployment.
```suggestion
approach attempts to strike a delicate balance between easing implementation
and providing support for formats that have historically had broad deployment.
```

2023-08-07 20:01 UTC, TallTed commented on index.html
> +include any members of the private information class, such as "d", as described
```suggestion
include any members of the private information class, such as `d`, as described
```

2023-08-07 20:01 UTC, TallTed commented on index.html
> +The `publicKeyJwk` property is OPTIONAL. If present, the value MUST
```suggestion
The `publicKeyJwk` property is OPTIONAL. If present, its value MUST
```

2023-08-07 20:01 UTC, TallTed commented on index.html
> +The `secretKeyJwk` property is OPTIONAL. If present, the value MUST be a <a
```suggestion
The `secretKeyJwk` property is OPTIONAL. If present, its value MUST be a <a
```

2023-08-07 20:01 UTC, TallTed commented on index.html
> +The `publicKeyMultibase` property is OPTIONAL. If present, the value MUST be a
```suggestion
The `publicKeyMultibase` property is OPTIONAL. If present, its value MUST be a
```

2023-08-07 20:01 UTC, TallTed commented on index.html
> +The `secretKeyMultibase` property is OPTIONAL. If present, the value MUST be a
```suggestion
The `secretKeyMultibase` property is OPTIONAL. If present, its value MUST be a
```

2023-08-08 22:59 UTC, OR13 approved these changes

2023-08-12 19:19 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging (into msporny-json-web-key PR).

2023-08-12 19:19 UTC, merged