Update domain to support arrays of domain values.
w3c/vc-data-integrity pull request #156
Opened 2023-08-06 19:38 UTC by msporny

This PR is an attempt to address issue #29 by updating the domain parameter to allow for arrays of domain values.

2023-08-06 20:13 UTC, dlongley approved these changes

2023-08-06 20:16 UTC, Wind4Greg approved these changes

2023-08-07 04:43 UTC, iherman approved these changes
Good thing is that this definition does not change the vocabulary due to the very nature of RDF (and because we never used the OWL cardinality constraints)

2023-08-07 20:04 UTC, TallTed requested changes

2023-08-07 20:04 UTC, TallTed commented on index.html
> +security domain known to the creator of the proof. Examples domain values
```suggestion
security domain known to the creator of the proof. Example domain values
```

2023-08-07 20:04 UTC, TallTed commented on index.html
> +An OPTIONAL property that conveys one or more security domains in which the
```suggestion
The `domain` property is OPTIONAL. It conveys one or more security domains in which the
```

2023-08-12 20:06 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-08-12 20:06 UTC, merged