Allow errors to be conveyed based on execution environment.
w3c/vc-data-integrity pull request #158
Opened 2023-08-06 20:45 UTC by msporny

This PR attempts to address issue #157 by allowing errors to be conveyed based on what the execution environment is capable of conveying.

2023-08-06 21:43 UTC, Wind4Greg approved these changes

2023-08-06 23:12 UTC, dlongley approved these changes

2023-08-07 04:50 UTC, iherman approved these changes

2023-08-07 20:22 UTC, TallTed requested changes

2023-08-07 20:22 UTC, TallTed commented on index.html
> +If not an error MUST be raised and SHOULD convey an error type of
```suggestion
If not, an error MUST be raised and SHOULD convey an error type of
```

2023-08-07 20:22 UTC, TallTed commented on index.html
>  If the <var>proof</var>.<var>created</var> is set and it deviates more than
```suggestion
If the <var>proof</var>.<var>created</var> is set and its value differs
from the datetime of verification by more than
```

2023-08-12 20:08 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-08-12 20:08 UTC, merged