Add guidance on context and URL caching in general
w3c/vc-data-integrity pull request #172
Opened 2023-08-19 16:19 UTC by msporny

This PR attempts to address issue #170, raised by PING and security review, by adding guidance on context and URL caching, in general. It also adds a security consideration and a privacy consideration on network requests and network request fingerprinting.

/cc @kdenhartog

2023-08-19 17:36 UTC, dlongley approved these changes
See comment trying to note the benefit of the use of URLs and acknowledgment that some production applications might need to load them.

2023-08-19 17:36 UTC, dlongley commented on index.html
> +a mismatch in privacy expectations among any entity that is not the creator of
```suggestion
a mismatch in privacy expectations for any entity that is not the creator of
```

2023-08-19 17:36 UTC, dlongley commented on index.html
> +achieve caching goals.
```suggestion
Implementations MAY load application-specific JSON-LD Context files from the
network during development, but SHOULD permanently cache JSON-LD Context files
utilized in <a>conforming documents</a> in production settings to increase the
security and privacy characteristics of solutions. Approaches to caching as
described above, or functionally equivalent mechanisms, MAY be utilized to
achieve caching goals.
        </p>
        <p>
Some applications, such as digital wallets that are capable of holding arbitrary
<a>verifiable credentials</a> (from any issuer, using any contexts) or other
data-integrity-protected documents, might need to be able to load externally
linked resources, such as JSON-LD Context files, in production settings. This is
expected to increase user choice, scalability, and decentralized upgrades in the
ecosystem over time. Authors of these applications are advised to read the
security and privacy sections of this document for further considerations.
        </p>
```

2023-08-20 23:05 UTC, Wind4Greg approved these changes
Good privacy advice.

2023-08-21 05:19 UTC, brianorwhatever approved these changes

2023-08-21 18:07 UTC, kdenhartog approved these changes
Text reads fine as is so approving. I'd suggest linking to https://github.com/ietf-wg-ohai/oblivious-http as one method to addressing privacy concerns when needing to resolve in production instances as well. There's others as well such as generic proxying through a trusted third party (e.g. wallets proxy requestthrough their backend services or mapping URL resolutions in wallet JSON-LD document loaders to trusted services where they can be resolved) that can be used as alternatives so it doesn't need to require any particular solution. The main thinking here is that suggesting solutions is more likely to lead to them getting addressed but the current text states this well enough in my opinion that it doesn't need to be blocked on this addition.

2023-08-21 20:01 UTC, TallTed requested changes
A number of grammar and language tweaks.

Note that `context/s` and `vocabulary/ies` are only capitalized in section titles in the JSON-LD spec, and I think that we should do the same. I have not applied this to the whole document, only to the areas touched by this PR. This might call for a distinct PR and/or Issue.

2023-08-21 20:01 UTC, TallTed commented on index.html
> +equivalent mechanism.
```suggestion
Authors of application-specific vocabularies and specifications SHOULD ensure
that their JSON-LD context and vocabulary files are permanently cacheable
using the approaches to caching described above or a functionally equivalent
mechanism.
```

2023-08-21 20:01 UTC, TallTed commented on index.html
> +achieve caching goals.
```suggestion
Implementations MAY load application-specific JSON-LD context files from the
network during development, but SHOULD permanently cache JSON-LD context files
used in <a>conforming documents</a> in production settings to increase their
security and privacy characteristics. Caching goals MAY be achieved through
approaches such as those described above or functionally equivalent mechanisms.
```

2023-08-21 20:01 UTC, TallTed commented on index.html
> +        </p>
```suggestion
Some applications, such as digital wallets, that are capable of holding arbitrary
<a>verifiable credentials</a> or other data-integrity-protected documents, from
any issuer and using any contexts, might need to be able to load externally
linked resources, such as JSON-LD context files, in production settings. This is
expected to increase user choice, scalability, and decentralized upgrades in the
ecosystem over time. Authors of such applications are advised to read the
security and privacy sections of this document for further considerations.
        </p>
```

2023-08-21 20:01 UTC, TallTed commented on index.html
>  Vocabularies, see <a data-cite="?VC-DATA-MODEL-2.0#base-context">Verifiable
Taking my `contexts` and `vocabularies` lowercasing cue from https://www.w3.org/TR/json-ld11/ where they are only capitalized in section titles.
```suggestion
For further information regarding processing of JSON-LD contexts and
vocabularies, see <a data-cite="?VC-DATA-MODEL-2.0#base-context">Verifiable
```

2023-08-21 20:01 UTC, TallTed commented on index.html
> +loaded from the network during or after verification.
```suggestion
This specification is designed in such a way that no network requests are
required when verifying a proof on a <a>conforming secured document</a>.
Readers might note, however, that <a href="#data-model">JSON-LD contexts</a>
and <a>verification methods</a> can contain URLs that might be retrieved
over a network connection. This concern exists for any URL that might be
loaded from the network during or after verification.
```

2023-08-21 20:01 UTC, TallTed commented on index.html
> +fetched from the network.
```suggestion
To the extent possible, implementers are urged to permanently or aggressively
cache such information to reduce the attack surface on an
implementation that might need to fetch such URLs over the network. For
example, caching techniques for <a href="#data-model">JSON-LD contexts</a> are
described in Section <a href="#contexts-and-vocabularies"></a>, and some
<a>verification methods</a>, such as `did:key` [[?DID-KEY]], do not need to be
fetched from the network at all.
```

2023-08-21 20:01 UTC, TallTed commented on index.html
> +When it is not possible to cache the information, such as when a specific HTTP
```suggestion
When it is not possible to use cached information, such as when a specific HTTP
```

2023-08-21 20:01 UTC, TallTed commented on index.html
> +        <h3>Network Request Fingerprinting</h3>
```suggestion
        <h3>Fingerprinting Network Requests</h3>
```

2023-08-21 20:01 UTC, TallTed commented on index.html
> +over a network connection.
```suggestion
Fingerprinting concerns exist for any URL that might be loaded from the network
during or after <a href="#verify-proof">proof verification</a>. This
specification is designed in such a way that no network requests are necessary
when verifying a proof on a <a>conforming secured document</a>. Readers might
note, however, that <a href="#data-model">JSON-LD contexts</a> and
<a>verification methods</a> can contain resource URLs that might be retrieved
over a network connection.
```

2023-08-21 20:01 UTC, TallTed commented on index.html
> +the document.
```suggestion
For example, creators of <a>conforming documents</a> might craft unique
per-document URLs for <a href="#data-model">JSON-LD contexts</a> and
<a>verification methods</a>. When verifying such a document, a verifier fetching
that information from the network would reveal their interest in the
<a>conforming document</a> to the creator of the document, which might lead to
a mismatch in privacy expectations for any entity that is not the creator of
the document.
```

2023-08-21 20:01 UTC, TallTed commented on index.html
> +suspected fingerprinting URLs.
```suggestion
when fetching URLs from the network. Additionally, heuristics might be used
to determine whether creators of <a>conforming documents</a> are using fingerprinting
URLs in a way that might violate privacy expectations. These heuristics could be
used to display warnings to entities that might process documents containing
suspected fingerprinting URLs.
```

2023-08-26 16:53 UTC, msporny commented
@kdenhartog wrote:
> I'd suggest linking to https://github.com/ietf-wg-ohai/oblivious-http as one method to addressing privacy concerns when needing to resolve in production instances as well. 

Added in https://github.com/w3c/vc-data-integrity/pull/172/commits/6eb08386692550e2e1cdfef95ba33bc823db7934.

2023-08-26 16:56 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-08-26 16:56 UTC, merged