Add section on Resource Integrity and `digestMultibase`.
w3c/vc-data-integrity pull request #174
Opened 2023-08-19 19:31 UTC by msporny

This PR attempts to address issue #170, raised by PING and security review, by adding a mechanism to identify resources by cryptographic hash such that they can be permanently cached, or not retrieved from the network if they already exist in a cache.  This PR builds on top of PR #172 and adds appropriate warnings that the digest mechanism might change during CR based on implementer feedback.

/cc @kdenhartog

2023-08-20 08:09 UTC, iherman approved these changes
1. We should make a note that the `digestMultibase` should be added as a new property into the vocabulary. The domain is unlimited, the range is... I guess a new datatype to be defined...
2. I wonder whether the (new) term, ie, `digestMultibase` should not be defined as "reserved" in the vocabulary at least until the discussion on SRI is closed. 

None of these two comments should hold up merging this PR, they can be picked up after that is done.

2023-08-20 16:24 UTC, dlongley approved these changes

2023-08-20 22:56 UTC, Wind4Greg approved these changes

2023-08-21 18:23 UTC, kdenhartog approved these changes
+1 to defining this feature within data-integrity. I could see it as being useful within then entire vc-data-model as well for claims. Since this text seems to be focused on handling of claims URLs, would it be possible to also highlight how this would be used for URLs within the  `@context` property as well or for other URLs which can't rely on additional JSON-LD properties? I suspect this has already been considered and I've just not been up to date on the different arguments being made on it so far.

2023-08-21 18:37 UTC, dmitrizagidulin approved these changes
:+1:

2023-08-21 18:44 UTC, longpd approved these changes
This looks good to go.

2023-08-21 20:14 UTC, TallTed requested changes
Editorial language and punctuation

2023-08-21 20:14 UTC, TallTed commented on index.html
> +The Working Group is currently attempting to determine if cryptographic hash
```suggestion
The Working Group is currently attempting to determine whether cryptographic hash
```

2023-08-21 20:14 UTC, TallTed commented on index.html
> +that is identified has not changed since the proof was created. This applies to
```suggestion
that is identified has changed since the proof was created. This applies to
```

2023-08-21 20:14 UTC, TallTed commented on index.html
> +To validate that a resource referenced by a <a>conforming secured document</a>
```suggestion
To enable confirmation that a resource referenced by a <a>conforming secured document</a>
```

2023-08-21 20:14 UTC, TallTed commented on index.html
> +SHA-3 with 384 bits (48 bytes) of output as defined by [[SHA3]].
```suggestion
SHA-2 with 256 bits (32 bytes) of output, as defined by [[RFC6234]].
              </td>
            </tr>
            <tr>
              <td>`sha2-384`</td>
              <td>`0x20`</td>
              <td>
SHA-2 with 384 bits (48 bytes) of output, as defined by [[RFC6234]].
              </td>
            </tr>
            <tr>
              <td>`sha3-256`</td>
              <td>`0x16`</td>
              <td>
SHA-3 with 256 bits (32 bytes) of output, as defined by [[SHA3]].
              </td>
            </tr>
            <tr>
              <td>`sha3-384`</td>
              <td>`0x15`</td>
              <td>
SHA-3 with 384 bits (48 bytes) of output, as defined by [[SHA3]].
```

2023-08-26 18:01 UTC, msporny commented
> 1. We should make a note that the `digestMultibase` should be added as a new property into the vocabulary. The domain is unlimited, the range is... I guess a new datatype to be defined...

The domain and range are unlimited (the property can be used with any subject). The datetype is multibase.

> 2. I wonder whether the (new) term, ie, `digestMultibase` should not be defined as "reserved" in the vocabulary at least until the discussion on SRI is closed.

Sure, we could do that, but if we do that, we should also put `digestSRI` as reserved as well.

2023-08-26 18:12 UTC, msporny commented
> +1 to defining this feature within data-integrity. I could see it as being useful within then entire vc-data-model as well for claims. Since this text seems to be focused on handling of claims URLs, would it be possible to also highlight how this would be used for URLs within the `@context` property as well or for other URLs which can't rely on additional JSON-LD properties?

We have a section in the VC Data Model on resource integrity as well, covering the use cases you mention:

https://w3c.github.io/vc-data-model/#integrity-of-related-resources

> I suspect this has already been considered and I've just not been up to date on the different arguments being made on it so far.

Yep, we already support what you suggest w/ VCs. Since the Data Integrity specification is at a lower level (and doesn't define application contexts), we provide at least two types of guidance: 1) provide cryptographic digests for your application contexts, and 2) permacache contexts; don't load them from the network. Those two types of guidance make it such that you shouldn't need the `relatedResource` feature for JSON-LD contexts... but, if for some reason you do, you can just define the feature in your application context and use that.

2023-08-26 18:15 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-08-26 18:15 UTC, merged