Align context URLs with vocabulary URLs.
w3c/vc-data-integrity pull request #186
Opened 2023-08-26 22:19 UTC by msporny

This PR attempts to address issue #177 by aligning all of the context URLs with the vocabulary URLs.

2023-08-27 09:22 UTC, iherman approved these changes

2023-08-27 17:02 UTC, dlongley approved these changes

2023-08-27 18:06 UTC, Wind4Greg approved these changes

2023-08-28 16:47 UTC, TallTed requested changes
Minor language tweak

2023-08-28 16:47 UTC, TallTed commented on index.html
>  One example of when context injection is expected to be unnecessary is when the Verifiable
```suggestion
Context injection is expected to be unnecessary sometimes, such as when the Verifiable
```

2023-09-02 16:20 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-09-02 16:20 UTC, merged