Updated vocabulary and diagram
w3c/vc-data-integrity pull request #189
Opened 2023-09-08 14:29 UTC by iherman

Now that the DI spec itself is ready for CR, this PR syncs up the vocabulary, including the diagram, with the spec. The changes are:

- The vocabulary (and the diagram) includes the `digestMultibase` term, with the caveat in the spec (whereby the term is at risk, and may change for `digestSRI`) copied into the vocabulary as well. Note that this is the only hard, content change in the vocabulary.
- The diagram changes discussed in #175 are now moved to the “real” branch
- There is now an alt text for the diagram

As usual, there is a [preview of the results](https://w3c.github.io/yml2vocab/previews/di/vocabulary.html)

2023-09-08 15:49 UTC, Wind4Greg approved these changes

2023-09-08 16:29 UTC, TallTed requested changes

2023-09-08 16:29 UTC, TallTed commented on vocab/security/template.html
> +          These style names are used in the explanation text in what follows.
```suggestion
          These style names are used in the explanation text that follows, below.
```

2023-09-08 16:29 UTC, TallTed commented on vocab/security/template.html
> +          and labeled as "Proof", respectively "VerificationMethod".
```suggestion
          The diagram is roughly divided into left and right sections 
          (although there are some common nodes; see later).
          To make this description easier to understand, these will be referred to as the 
          "Proof Section" and the "Verification Section". 
          Each of these sections has an ellipse at the top, styled as Class, 
          and respectively labeled as "Proof" and "VerificationMethod".
```

2023-09-08 16:29 UTC, TallTed commented on vocab/security/template.html
> +            to the ellipse labeled as "Proof" with a connecting line styled as Contains.
`styled as Contains` makes me think the key should be changed from `Graph Containment`, which change I was going to suggest anyway.

2023-09-08 16:29 UTC, TallTed commented on vocab/security/template.html
> +            "cryptosuiteString".
```suggestion
            There are two more ellipses in this section, styled as Class 
            and labeled as "Ed25519Signature2020" and "DataIntegrityProof",
            each connected to the ellipse labeled as "Proof"
            with connecting lines styled as Superclass. 
            The ellipse labeled as "DataIntegrityProof" is
            also connected to a box styled as Property, 
            and labeled as "cryptosuite", with a connecting 
            line styled as Domain Of. The "cryptosuite" Property box
            is connected to a shape
            styled as Datatype and labeled as
            "cryptosuiteString", with a connecting 
            line styled as Range.
```

2023-09-08 16:29 UTC, TallTed commented on vocab/security/template.html
> +            connects to the same Datatype shape with a connecting line styled as Range.
```suggestion
            The box labeled as "proofValue" is connected to a shape styled as Datatype
            and labeled as "multibase", with a connecting line styled as Range.
            Finally, another box, styled as Property and labeled as "digestMultibase",
            is connected to the same "multibase" Datatype shape with
            a connecting line styled as Range.
```

2023-09-08 16:29 UTC, TallTed commented on vocab/security/template.html
> +          <h3>VefiricationMethod Section</h3>
```suggestion
          <h3>VerificationMethod Section</h3>
```

2023-09-08 16:29 UTC, TallTed commented on vocab/security/template.html
> +            the ellipse labeled "VerificationMethod".
```suggestion
            The right side of this Section contains a column of labeled boxes, 
            all styled as Property. The labels, from top to bottom, are 
            "verificationMethod", "authentication", "assertionMethod", 
            "capabilityDelegation", "capabilityInvocation", and "keyAgreement". 
            Each of these boxes is connected to 
            the ellipse labeled "VerificationMethod",
            with a connecting line styled as Range.
```

2023-09-08 16:29 UTC, TallTed commented on vocab/security/template.html
> +          </p>
```suggestion
            The left side of this Section contains a column of three labeled 
            boxes, all styled as Property. The labels, from top to bottom, are 
            "expires", "controller", and "revoked". Each of these is connected
            to the ellipse labeled "VerificationMethod",
            with connecting lines styled as Domain Of.
            The "expires" Property box is also connected to the ellipse 
            labeled "Proof" in the Proof Section, with a connecting line 
            styled as Domain Of.
          </p>
```

2023-09-08 16:29 UTC, TallTed commented on vocab/security/template.html
> +            the ellipse labeled as "VerificationMethod" with a connecting line styled as Superclass.
```suggestion
            The middle of this section contains three ellipses,
            styled as Class, and labeled as 
            "Multikey, "Ed25519VerificationKey2020", and "JsonWebKey".
            Each of these is connected to 
            the ellipse labeled as "VerificationMethod"
            with a connecting line styled as Superclass.
```

2023-09-08 16:29 UTC, TallTed commented on vocab/security/template.html
> +            to the shape styled as Datatype and labeled as "multibase", referred to in the Proof Section.
```suggestion
            Two boxes, styled as Property and labeled as "secretKeyMultibase"
            and "publicKeyMultibase", are connected to the ellipse
            labeled as "Multikey" with a connecting line styled as Domain Of.
            Each of these boxes is also connected to the shape in the Proof
            section styled as Datatype and labeled as "multibase",
            with connecting lines styled as Range.
```

2023-09-08 16:29 UTC, TallTed commented on vocab/security/template.html
> +            a shape styled as Datatype and labeled as "rdf:JSON".
```suggestion
            Finally, two boxes, styled as Property and labeled "secretKeyJwk" 
            and "publicKeyJwk", are connected to the ellipse labeled "JsonWebKey"
            with a connecting line styled as Domain Of. 
            Each of these boxes is also connected to
            a shape styled as Datatype and labeled as "rdf:JSON",
            with connecting lines styled as Range.
```

2023-09-09 06:56 UTC, iherman commented on vocab/security/template.html
> +            to the ellipse labeled as "Proof" with a connecting line styled as Contains.
@TallTed I agree, but I would prefer to move that into a separate issue. The reason is that, for consistency's sake, this change should also be done in the VCDM, both in the descriptions and on the diagrams, and I do not want to mess up this PR for that. Would you agree? If so, can you put that into a separate issue? Thx.

2023-09-18 14:56 UTC, msporny approved these changes

2023-09-18 14:57 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2023-09-18 14:57 UTC, merged

2023-09-18 19:55 UTC, TallTed commented on vocab/security/template.html
> +            to the ellipse labeled as "Proof" with a connecting line styled as Contains.
https://github.com/w3c/vc-data-integrity/issues/203