Add section on previous proof privacy consideration.
w3c/vc-data-integrity pull request #198
Opened 2023-09-15 21:19 UTC by msporny

This PR is an attempt to address issue #168 by highlighting a privacy consideration raised by PING and suggests a mechanism that could mitigate the concern.

2023-09-16 08:15 UTC, kdenhartog approved these changes
Lgtm good ideal to add a suggested mitigation strategy too.

2023-09-16 15:13 UTC, dlongley approved these changes

2023-09-16 18:07 UTC, Wind4Greg approved these changes

2023-09-18 19:12 UTC, TallTed requested changes

2023-09-18 19:12 UTC, TallTed commented on index.html
> +entity that added the previous proof.
```suggestion
When using the `previousProof` feature defined in
<a href="#proof-chains"></a>, implementations are required to digitally sign
over one or more previous proofs, so as to include them in the
secured payload. This inevitably exposes information related to each
entity that added a previous proof.
```

2023-09-18 19:12 UTC, TallTed commented on index.html
> +adding a non-repudiable digital signature on a document of any kind.
```suggestion
At minimum, the <a>verification method</a> for the previous proof, such as a
public key, is seen by the creator of the next proof in a proof chain. This
can be a privacy concern if the creator of the previous proof did not intend
to be included in a proof chain, but is an inevitable outcome when
adding a non-repudiable digital signature to a document of any kind.
```

2023-09-18 19:12 UTC, TallTed commented on index.html
> +to mitigate the privacy concern raised in this section.
```suggestion
It is possible to use more advanced cryptographic mechanisms, such as a
<a href="https://en.wikipedia.org/wiki/Group_signature">group signature</a>,
to hide the identity of the signer of a message, 
and it is also possible for a Data Integrity cryptographic suite
to mitigate this privacy concern.
```

2023-09-25 15:17 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2023-09-25 15:17 UTC, merged