i18n Improvements
w3c/vc-data-integrity pull request #240
Opened 2024-01-18 17:25 UTC by Wind4Greg

Add time zone info to optional `created` and `expires` properties for i18n compatibility. 

This PR addresses issue https://github.com/w3c/vc-di-bbs/issues/114 in the `vc-di-bbs` specification. The solution is not for that specification to redefine the `created` and `expires` properties but to reference the `vc-data-integrity` specification for them.  The i18n discussion on that issue recommended adding time zone information to these fields as this PR does.

2024-01-18 19:22 UTC, dlongley approved these changes
This is fine with me -- we could also link here: https://w3c.github.io/vc-data-model/#representing-time if others think that's a good idea too.

2024-01-19 07:06 UTC, iherman approved these changes

2024-02-04 23:20 UTC, msporny commented on index.html
> +zone offset, preferably Z (meaning UTC).
Hmm, I believe the change is redundant.  `dateTimeStamp` values MUST include a zone offset per https://www.w3.org/TR/xmlschema11-2/#dateTimeStamp

We also shouldn't deviate from the guidance given in the vc-data-model, namely:

https://w3c.github.io/vc-data-model/#representing-time

You might look at the definition for validity periods in vc-data-model for appropriate wording: https://w3c.github.io/vc-data-model/#validity-period

2024-02-04 23:20 UTC, msporny requested changes
Hmm, I believe the change is redundant. dateTimeStamp values MUST include a zone offset per https://www.w3.org/TR/xmlschema11-2/#dateTimeStamp

We also shouldn't deviate from the guidance given in the vc-data-model, namely:

https://w3c.github.io/vc-data-model/#representing-time

You might look at the definition for validity periods in vc-data-model for appropriate wording: https://w3c.github.io/vc-data-model/#validity-period

2024-02-09 17:44 UTC, msporny commented on index.html
> +zone offset, preferably Z (meaning UTC).
```suggestion
specified as an [[XMLSCHEMA11-2]] `dateTimeStamp` string, either in Universal Coordinated Time (UTC), denoted by a Z at the end of the value, or with a time zone offset relative to UTC. Time values that are incorrectly serialized without an offset MUST be interpreted as UTC.
```

2024-02-09 17:45 UTC, msporny commented on index.html
> +SHOULD include a zone offset, preferably Z (meaning UTC).
```suggestion
The `expires` property is OPTIONAL and, if present, specifies when the proof
expires. If present, it MUST be an [[XMLSCHEMA11-2]] `dateTimeStamp` string, either in Universal Coordinated Time (UTC), denoted by a Z at the end of the value, or with a time zone offset relative to UTC. Time values that are incorrectly serialized without an offset MUST be interpreted as UTC.
```

2024-02-09 18:20 UTC, TallTed commented on index.html
> +zone offset, preferably Z (meaning UTC).
@msporny's suggestion with line breaks as recommended...
```suggestion
specified as an [[XMLSCHEMA11-2]] `dateTimeStamp` string, either in Universal
Coordinated Time (UTC), denoted by a Z at the end of the value, or with a time
zone offset relative to UTC. Time values that are incorrectly serialized without
an offset MUST be interpreted as UTC.
```

2024-02-09 18:21 UTC, TallTed commented on index.html
> +SHOULD include a zone offset, preferably Z (meaning UTC).
@msporny's suggestion with line breaks as recommended...
```suggestion
The `expires` property is OPTIONAL and, if present, specifies when the proof
expires. If present, it MUST be an [[XMLSCHEMA11-2]] `dateTimeStamp` string,
either in Universal Coordinated Time (UTC), denoted by a Z at the end of the
value, or with a time zone offset relative to UTC. Time values that are
incorrectly serialized without an offset MUST be interpreted as UTC.
```

2024-02-19 22:38 UTC, msporny approved these changes

2024-02-19 22:38 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2024-02-19 22:39 UTC, merged