Editorial changes on the vocabulary tables to make it consistent with the VCDM
w3c/vc-data-integrity pull request #255
Opened 2024-03-14 15:48 UTC by iherman

The changes mean:

- Changing the font-style of hash values to `<code>`
- Add the openssl command line text after the context file table, using the same language as in the VCDM
- Changing the openssl command after the vocabulary table to use the same language as well
- Removing the sha3 hashes (following https://github.com/w3c/vc-data-model/pull/1459 and https://github.com/w3c/vc-data-model/issues/1455)
- Minor language adjustments in the text.

2024-04-05 19:47 UTC, dlongley approved these changes

2024-04-05 20:30 UTC, TallTed requested changes

2024-04-05 20:30 UTC, TallTed commented on index.html
> +the JSON-LD serialization of the vocabulary URL as already resolved, where the resolved document matches
I think `resolved` here should be `dereferenced`, which *includes* resolving as well as retrieving the target document, which retrieval is the part that's really expected to be not done at runtime.
```suggestion
the JSON-LD serialization of the vocabulary URL as already dereferenced, where the dereferenced document matches
```

2024-04-09 13:49 UTC, TallTed approved these changes

2024-04-28 14:22 UTC, msporny approved these changes

2024-04-28 14:22 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-04-28 14:22 UTC, merged