Updated the section on multikey
w3c/vc-data-integrity pull request #257
Opened 2024-03-15 11:28 UTC by iherman

This PR is, primarily, to cover issue #251:

- It adds a remark both for `publicKeyMultibase` and `secretKeyMultibase` that the value, which is encoded in Multibase, must be specified by the cryptosuite spec
- It also adds, both for Multibase and Multikey, that a specific context file must be used for JSON-LD processing (that was not made clear before...)
- There were some erroneous context files in the examples...

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-integrity/pull/257.html" title="Last updated on Mar 15, 2024, 12:04 PM UTC (f1e7e42)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-integrity/257/2098949...f1e7e42.html" title="Last updated on Mar 15, 2024, 12:04 PM UTC (f1e7e42)">Diff</a>

2024-03-15 11:54 UTC, TallTed requested changes
Trivial

2024-03-15 11:54 UTC, TallTed commented on index.html
> +Multibase encoded value as described in Section [[[#multibase-0]]]. The value format itself,
```suggestion
Multibase-encoded value as described in Section [[[#multibase-0]]]. The value format itself,
```

2024-03-15 11:54 UTC, TallTed commented on index.html
> +Multibase encoded value as described in Section [[[#multibase-0]]]. The value format itself,
```suggestion
Multibase-encoded value as described in Section [[[#multibase-0]]]. The value format itself,
```

2024-03-15 14:34 UTC, Wind4Greg approved these changes

2024-03-15 14:46 UTC, TallTed approved these changes

2024-03-17 20:57 UTC, dlongley approved these changes

2024-04-28 14:24 UTC, msporny approved these changes

2024-04-28 14:25 UTC, msporny commented
Editorial (new normative statements are clarifying, implementations won't need to change), multiple reviews, changes requested and made, no objections, merging.

2024-04-28 14:25 UTC, merged