Explain difference between VM in proof and controller document.
w3c/vc-data-integrity pull request #269
Opened 2024-06-19 22:00 UTC by msporny

This PR is an attempt to address issue #187 by explaining the difference between the `verificationMethod` property as it is used in a `proof` and the property as it is used in a controller document.

/cc @identitywoman

2024-06-20 14:55 UTC, dlongley approved these changes

2024-06-20 15:27 UTC, Wind4Greg approved these changes

2024-06-21 20:48 UTC, David-Chadwick approved these changes

2024-06-24 21:00 UTC, TallTed requested changes

2024-06-24 21:00 UTC, TallTed commented on index.html
>  such as `cryptosuite` might provide a mechanism by which to obtain the required
```suggestion
such as `cryptosuite` might provide a mechanism by which to obtain the information
```

2024-06-24 21:00 UTC, TallTed commented on index.html
> +of the data. That is, the `verificationMethod` references, via a URL, the
```suggestion
necessary to verify the proof. Note that when `verificationMethod` is
expressed in a [=data integrity proof=], the value points to the actual location
of the data; that is, the `verificationMethod` references, via a URL, the
```

2024-06-24 21:00 UTC, TallTed commented on index.html
>  context (`https://www.w3.org/ns/credentials/v2`) includes it.
I'm not sure whether we're blurring `hash` and `digest` and/or maybe mis-referring to one or the other. I may also have fumbled the data cite markup, but hopefully the suggestion is clear enough to repair.
```suggestion
JSON-LD context authors are expected to add `digestMultibase` to contexts that will
be used in documents that refer to other resources and to include an associated
cryptographic digest. For example, the [[[VC-DATA-MODEL-2.0]]] refers to
context (`https://www.w3.org/ns/credentials/v2`) which includes
`digestMultibase`, and the [[[VC-DATA-MODEL-2.0]]] includes
<data cite="VC-DATA-MODEL-2.0/#base-context">the hexadecimal encoded
SHA2-256 digest value</data> of that context document.
```

2024-06-27 18:56 UTC, msporny commented on index.html
>  context (`https://www.w3.org/ns/credentials/v2`) includes it.
Yes, we were unnecessarily blurring the lines. I have unblurred them by using "digest" or "cryptographic digest" and made the modification into your change suggestion.

2024-06-27 18:58 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-06-27 18:58 UTC, merged