Add Security Considerations section on Protected Information.
w3c/vc-data-integrity pull request #271
Opened 2024-06-21 15:53 UTC by msporny

This PR is an attempt to address issue #215 by explaining what information is protected by a data integrity proof.

2024-06-21 16:38 UTC, dlongley approved these changes

2024-06-21 16:58 UTC, longpd approved these changes

2024-06-21 20:18 UTC, David-Chadwick approved these changes

2024-06-22 00:40 UTC, Wind4Greg approved these changes

2024-06-22 03:48 UTC, iherman approved these changes

2024-06-24 21:52 UTC, TallTed requested changes

2024-06-24 21:52 UTC, TallTed commented on index.html
> +particular [=cryptosuite=]. This protection mechanism is in contrast to some
```suggestion
particular [=cryptosuite=]. This protection mechanism differs from some
```

2024-06-24 21:52 UTC, TallTed commented on index.html
> +mechanisms do not have this capability.
```suggestion
signed. One benefit of this approach is that the cryptographic signature is
portable to a variety of different syntaxes, such as JSON, YAML, and CBOR,
without invalidating the signature. More traditional cryptographic signature
mechanisms do not have this capability.
```

2024-06-24 21:52 UTC, TallTed commented on index.html
> +that has confirmed that all data returned has been successfully protected.
There might instead be some presumption which was inadvertently omitted from "presume ... information", and which restoration would make this sentence make more sense.
```suggestion
Implementers and developers are urged to not trust information
that contains a [=data integrity proof=] unless the proof has been [=verified=]
and the verified data is provided in a return value from a software library
that has confirmed that all data returned has been successfully protected.
```

2024-06-27 21:59 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-06-27 21:59 UTC, merged