Remove duplicated text from Controller Document spec.
w3c/vc-data-integrity pull request #277
Opened 2024-06-30 19:44 UTC by msporny

This PR removes all duplicated text from the [Controller Document specification](https://w3c.github.io/controller-document/) and updates all references to use the controller document spec.

2024-07-01 02:30 UTC, Wind4Greg approved these changes

2024-07-01 15:12 UTC, iherman approved these changes
Is it possible to explicitly ping me when (a) this is merged and (b) the corresponding definitions are in the controller document? I will have to update the vocabulary documents...

Thank you.

2024-07-01 15:12 UTC, iherman commented on index.html
> +    </section>
As a result of the removal in the section, the 'Acknowledgement' section is empty. This looks a bit odd. If we intend to add some things then, we should do it asap, otherwise we should remove the section altogether.

2024-07-01 16:16 UTC, TallTed commented
> This PR removes all duplicated text from the [Controller Document specification](https://w3c.github.io/controller-document/)

I believe that should be read (and perhaps rewritten) as, "This PR removes all text from the [Data Integrity specification](https://w3c.github.io/vc-data-integrity/) that duplicates text [now] found in the [Controller Document specification](https://w3c.github.io/controller-document/)."

(As written, it says that it's removing [duplicated] text (presumably text that is present twice therein) *from* the [Controller Document specification](https://w3c.github.io/controller-document/), which would be exceedingly odd here in the Data Integrity repository!)

The title should probably also be rewritten, along the lines of `Remove text that duplicates text in Controller Document spec`.

2024-07-01 16:35 UTC, TallTed requested changes
Editorial, grammar and such

2024-07-01 16:35 UTC, TallTed commented on index.html
>  a single string value, or an array of string values that are
travels with the change below
```suggestion
a single string value, or an array of string values, each of which is a
```

2024-07-01 16:35 UTC, TallTed commented on index.html
> +<a data-cite="CONTROLLER-DOCUMENT#multihash">Multihash</a> values.
travels with the change above
```suggestion
<a data-cite="CONTROLLER-DOCUMENT#multihash">Multihash</a> value.
```

2024-07-01 16:35 UTC, TallTed commented on index.html
> +enhances privacy.
```suggestion
between the revocation information associated with a [=verifiable credential=],
and the <a data-cite="CONTROLLER-DOCUMENT#dfn-revoked">revocation</a>
and <a data-cite="CONTROLLER-DOCUMENT#defn-vm-expires">expiration</a> times
for a [=verification method=]. The
<a data-cite="CONTROLLER-DOCUMENT#dfn-revoked">revocation</a> and
<a data-cite="CONTROLLER-DOCUMENT#defn-vm-expires">expiration</a> times for a
[=verification method=] are expressed using the `revocation` and `expires`
properties, respectively; are related to events such as a private key being
compromised or expiring; and can provide timing information which might reveal
details about a controller such as their security practices or when they might
have been compromised. The revocation information for a [=verifiable
credential=] is expressed using the `credentialStatus` property; is related
to events such as an individual losing the privilege that is granted by the
[=verifiable credential=]; and does not provide timing information, which
enhances privacy.
```

2024-07-01 16:35 UTC, TallTed commented on index.html
> +mechanisms.
```suggestion
used by [=conforming secured documents=] in production settings, to increase
their security and privacy characteristics. Goals of processing speed MAY be
achieved through caching approaches such as those described above or
functionally equivalent mechanisms.
```

2024-07-01 16:35 UTC, TallTed commented on index.html
> +The process for verification relationship validation is outlined in
```suggestion
The process of validating a verification relationship is outlined in
```

2024-07-01 19:01 UTC, msporny commented on index.html
> +    </section>
It's empty for now, but it will be filled w/ content related to the funding sources that were used to develop the specification as well as everyone that participated in the discussion of this specification (issue/PR commenters, etc.)

In order to do that, though, I need to update my script that crawls the history and extracts all parties that were involved in issues/PRs (and I don't have the spare cycles to do that now). I agree that we need to add/update this section very soon now. 

An issue needs to be raised for this (and I have to run to another call right now). Will try to remember to do it later, or maybe you will win the race to raise the issue? :P

2024-07-01 20:04 UTC, TallTed requested changes

2024-07-01 20:04 UTC, TallTed commented on index.html
>  details about a controller such as their security practices or when they might
Missed this the first time...
```suggestion
details about a controller, such as their security practices or when they might
```

2024-07-01 20:15 UTC, longpd approved these changes
With TallTeds's grammatical changes and Manu's completion of the Acknowledgments I support PR.

2024-07-07 15:58 UTC, msporny commented on index.html
> +    </section>
Issue #282 raised to address this concern.

2024-07-07 15:59 UTC, msporny commented
Editorial, multiple reviews, changes requested and made (and issues raised to track unresolved issues), no objections, merging.

2024-07-07 16:00 UTC, merged