Add expires example to proof.
w3c/vc-data-integrity pull request #314
Opened 2024-10-02 20:18 UTC by msporny

This PR is an attempt to address issue #313 by adding a proof to the specification that uses the `expires` property. 

/cc @filip26

2024-10-02 20:44 UTC, TallTed requested changes
Attempting to increase the clarity of the title

2024-10-02 20:44 UTC, TallTed commented on index.html
> +        title="A proof attached to a data document that uses the 'expires' property">
```suggestion
        title="A proof that uses the 'expires' property, attached to a data document">
```

2024-10-02 20:44 UTC, TallTed commented on index.html
> +        title="A proof attached to a data document that uses the 'expires' property">
or
```suggestion
        title="A data document with an attached proof that uses the 'expires' property">
```

2024-10-03 01:37 UTC, dlongley approved these changes

2024-10-03 01:37 UTC, dlongley commented on index.html
> +    <span class="comment">// the proof expires a month after it was issued</span>
```suggestion
    <span class="comment">// the proof expires a month after it was created</span>
```

2024-10-03 01:37 UTC, dlongley commented on index.html
> +    <span class="highlight">expires": "2020-07-11T19:14:04Z"</span>,
```suggestion
    <span class="highlight">"expires": "2020-07-11T19:14:04Z"</span>,
```

2024-10-03 15:44 UTC, iherman approved these changes

2024-10-03 16:50 UTC, Wind4Greg approved these changes

2024-10-14 21:33 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-10-14 21:33 UTC, merged