Define ControllerDocument class.
w3c/vc-data-integrity pull request #320
Opened 2024-11-16 18:30 UTC by msporny

This PR is an attempt to address issue https://github.com/w3c/controller-document/issues/117 by defining a ControllerDocument class. 

/cc @filip26

2024-11-16 19:08 UTC, dlongley approved these changes

2024-11-17 11:16 UTC, iherman commented
The PR is incomplete, because the diagram must be updated as well and. It is also a question whether the domain of the "controller" property shouldn't be specified as a union (ie, logical 'or') for a controller document class and the verification method class.

@msporny I think I should take it over, because I have more practice in creating/changing the diagram. I will clone your branch and take it from there if you are fine with it.

2024-11-17 18:14 UTC, msporny commented
> @msporny I think I should take it over, because I have more practice in creating/changing the diagram. I will clone your branch and take it from there if you are fine with it.

Yes, please take it over @iherman ... and thank you! :)

2024-11-19 08:00 UTC, iherman commented
> > It is also a question whether the domain of the "controller" property shouldn't be specified as a union (ie, logical 'or') for a controller document class and the verification method class.
> 
> I don't think we should limit the domain just yet... controller might make sense in many more use cases.
> 
> > @msporny I think I should take it over, because I have more practice in creating/changing the diagram. I will clone your branch and take it from there if you are fine with it.
> 
> Yes, please take it over @iherman ... and thank you! :)

Done.

2024-11-19 08:00 UTC, iherman approved these changes

2024-11-19 15:59 UTC, TallTed requested changes
The redundant department of redundancy department thanks you for your support.

2024-11-19 15:59 UTC, TallTed commented on vocab/security/template.html
> +          labeled as "VerificationMethod".
```suggestion
          and "VerificationRelationship", respectively. The Verification Method section
          includes an additional ellipse, labeled as "ControllerDocument", side-by-side with the ellipse
          labeled as "VerificationMethod".
```

2024-11-19 15:59 UTC, TallTed commented on vocab/security/template.html
> +            both these extra connections are also with a line styled as "Domain Of".
```suggestion
            both of these extra connecting lines are styled as "Domain Of".
```

2024-11-23 18:34 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-11-23 18:34 UTC, merged