Add "How it Works" section
w3c/vc-data-integrity pull request #47
Opened 2022-08-28 20:49 UTC by msporny

This PR adds a section called "How it Works" to the Data Integrity specification to conceptually describe how the technology described by the specification works.

There are a few images in the PR, so I'm attaching a screen shot for how the rendered diagram looks:

![image](https://user-images.githubusercontent.com/108611/187093914-187802a1-75fc-4736-9f6f-087405ad0547.png)

At present, the section is a bit out of place, and probably belongs more in the Introduction than in this section. I'll do an Editorial move later once we've agreed to the content.

2022-08-29 16:19 UTC, TallTed commented on index.html
> +To verify a cryptographic proof data is transformed, hashed, and
```suggestion
To verify a cryptographic proof, data is transformed, hashed, and
```

2022-08-29 16:30 UTC, TallTed requested changes
Mostly minor punctuation and grammar.

2022-08-29 16:30 UTC, TallTed commented on index.html
> +proof. The diagram is layed out left to right with a blue box labeled 'Data'
```suggestion
proof. The diagram is laid out left to right with a blue box labeled 'Data'
```

2022-08-29 16:30 UTC, TallTed commented on index.html
> +To create a cryptographic proof data is transformed, hashed, and
```suggestion
To create a cryptographic proof, data is transformed, hashed, and
```

2022-08-29 16:30 UTC, TallTed commented on index.html
> +BLAKE-3</a>. <dfn class="lint-ignore">Proof Generation</dfn> is a process that
```suggestion
BLAKE-3</a>.
        </p>

        <p>
<dfn class="lint-ignore">Proof Generation</dfn> is a process that
```

2022-08-29 16:30 UTC, TallTed commented on index.html
> +binary-to-text</a> encoding. <dfn>Hashing</dfn> is a process that calculates an
```suggestion
binary-to-text</a> encoding.
        </p>

        <p>
<dfn>Hashing</dfn> is a process that calculates an
```

2022-08-29 16:30 UTC, TallTed commented on index.html
> +process is conceptually similar to how a wax seal can be used on an envelope
```suggestion
process is conceptually similar to the way a wax seal can be used on an envelope
```

2022-08-29 16:30 UTC, TallTed commented on index.html
> +containing a letter to establish trust in the sender and that the letter has not
```suggestion
containing a letter to establish trust in the sender and show that the letter has not
```

2022-08-29 16:30 UTC, TallTed commented on index.html
> +proof. The diagram is layed out left to right with a blue box labeled
```suggestion
proof. The diagram is laid out left to right with a blue box labeled
```

2022-08-29 16:30 UTC, TallTed commented on index.html
> +'Data with Proof' on the very left. The blue box travels, left to right, through
```suggestion
'Data with Proof' on the far left. The blue box travels, left to right, through
```

2022-08-29 16:30 UTC, TallTed commented on index.html
> +on the very left. The blue box travels, left to right, through three subsequent
```suggestion
on the far left. The blue box travels, left to right, through three subsequent
```

2022-08-29 16:30 UTC, TallTed commented on index.html
> +conceptually the same as described above. <dfn class="lint-ignore">Proof
```suggestion
conceptually the same as described above.
        </p>

        <p>
<dfn class="lint-ignore">Proof
```

2022-08-29 16:30 UTC, TallTed commented on index.html
> +trusted by applying a cryptographic proof verification function. Possible
```suggestion
Verification</dfn> is a process that applies a cryptographic proof
verification function to see if the input data can be trusted. Possible
```

2022-08-29 16:30 UTC, TallTed commented on index.html
> +purposes of protecting the integrity of their data in transit and at rest.
```suggestion
purposes of protecting the integrity of application data in transit and at rest.
```

2022-08-29 16:36 UTC, decentralgabe approved these changes
nice work, this is easy to read and comprehensive

2022-08-29 17:51 UTC, dlongley approved these changes
I think this is a good start. We'll want to make sure that the description here also cleanly maps to what happens with BBS signatures, for example. In BBS signatures, transformation occurs, but the transformed data produces N messages that are hashed and signed, i.e., there are multiple signatures. This still seems to map to me but we'll have to see if others agree, ideally from the BBS suite spec writers.

2022-08-29 17:58 UTC, msporny commented
> In BBS signatures, transformation occurs, but the transformed data produces N messages that are hashed and signed, i.e., there are multiple signatures.

Yes, I cringed in the same way when I re-read the text yesterday. I do think we'll need to do some minor modifications to handle the "hash N messages" case. I'll try to put that in a revision before merging.

2022-08-30 08:49 UTC, iherman approved these changes
My comment is purely stylistic and, I admit, picky... (I approve the text regardless of taking this comment or not)

The sentence:

> This process is conceptually similar to...

is trying to provide an analogy to a reader who is unfamiliar with the concept of digital signatures and/or proofs of stake. And that is fine. However, wouldn't it be better, for consistency's sake, to add a similar analogy for what a hash function means? (I guess we can get away without an analogy for the transformation bit.)

2022-08-31 17:18 UTC, mprorock approved these changes
awesome improvement!

2022-09-04 15:52 UTC, msporny commented
> However, wouldn't it be better, for consistency's sake, to add a similar analogy for what a hash function means? (I guess we can get away without an analogy for the transformation bit.)

I have added this here: 0c83e1ccbfe665a612752ab8c62ee25eff58a8c0

2022-09-04 15:57 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2022-09-04 15:57 UTC, merged