Refactor Generate Proof algorithm.
w3c/vc-data-integrity pull request #62
Opened 2022-10-09 21:23 UTC by msporny

This PR refactors the generalized form of the generate proof algorithm to align it with the latest implementation experience. The changes include:

* Upgrade to new terminology that was defined in previous PRs over the past several months.
* Tighten up language to be more precise about when calls are being made to cryptosuites.
* Add checking for error cases to ensure generated proofs by cryptosuites are valid.
* Use `var`s instead of `code`s to enable highlighting of variables in algorithms (to see where they are used more easily).

2022-10-10 06:53 UTC, iherman commented
I am a bit out of my depth here, but I will ask it anyway... Are we sure that _all_ crypto suites have an associated transformation? Because if not, then step (2) might have to be made more precise saying that if no such transformation is defined, then _transformedDocument_ is equal to _unsecuredDocument_.

2022-10-10 15:26 UTC, msporny commented
> I am a bit out of my depth here, but I will ask it anyway... Are we sure that _all_ crypto suites have an associated transformation? Because if not, then step (2) might have to be made more precise saying that if no such transformation is defined, then _transformedDocument_ is equal to _unsecuredDocument_.

Yes, good point. This section: 

https://pr-preview.s3.amazonaws.com/w3c/vc-data-integrity/pull/62.html#cryptographic-suites

... does state:

> The specification MUST detail the [transformation algorithms](https://pr-preview.s3.amazonaws.com/w3c/vc-data-integrity/pull/62.html#dfn-transformation-algorithm) (if any), parameters, and other necessary details, used to modify input data into the data to be protected.

Note the "if any" language. That said, it's fairly weak and we probably can't depend on people being able to remember that when reading the algorithms. 

I'll add text noting that a transformation might not need to be performed (though, I can't think of a realistic case where that's true). The only possibility I can think of is an "append-only" signing format, of which I can't think of a single implemented example. Think of something like NQuads or TURTLE, but with text appended to the end that's the digital proof.

2022-10-10 15:56 UTC, dlongley commented
I haven't had a chance to look closely at this yet, but one thing we need to keep in mind is that we need to allow for cryptosuites to define how individual parts of the document can be hashed and signed independently, e.g., BBS signatures / other selective disclosure cryptosuites.

2022-10-10 17:03 UTC, msporny commented
> I haven't had a chance to look closely at this yet, but one thing we need to keep in mind is that we need to allow for cryptosuites to define how individual parts of the document can be hashed and signed independently, e.g., BBS signatures / other selective disclosure cryptosuites.

Yes, I specified "hashData" to be "that thing". It should hold for BBS... that is, when you canonicalize for BBS, the "hashData" could be a hash-per-line (as defined by the `bbs-2023` cryptosuite), which would then be passed into the BBS signature algorithm. It's a bit of a handwave, but the algorithm in this section is the generalized one (so people don't have to keep writing out the basic steps and can instead just specify the transformation, hashing, and signature algorithms in their cryptosuite specs. That said, we might come to the conclusion that having algorithms split between the Data Integrity spec and each cryptosuite spec is confusing and instead we should allow each cryptosuite spec to fully define the full start-to-end algorithm. The danger there being that they can then generate proofs that look nothing like a data integrity proof.

So, there is some enforcement of the "shape" of a data integrity proof in the Data Integrity spec, with the details of how to generate that `proof` value deferred to the cryptosuites.

2022-10-12 19:14 UTC, mprorock approved these changes

2022-10-12 21:05 UTC, TallTed requested changes
A few tweaks, hopefully improving clarity...

2022-10-12 21:05 UTC, TallTed commented on index.html
> +to at least one second, in Universal Time Code format. A
```suggestion
<dfn>unsecured data document</dfn>. Required inputs are an
<a>unsecured data document</a> (<var>unsecuredDocument</var>) and
<a>proof options</a> (<var>options</var>). The
<a>proof options</a> MUST contain an identifier for the
<a>cryptographic suite</a> (<var>cryptosuite</var>); an identifier for the
<a>verification method</a> (<var>verificationMethod</var>) that can be used to
verify the authenticity of the proof; and an [[!XMLSCHEMA11-2]] combined date and
time string (<var>created</var>) containing the current date and time, accurate
to at least one second, in Universal Time Code format. A
```

2022-10-12 21:05 UTC, TallTed commented on index.html
> +PROOF_GENERATION_ERROR MUST be raised.
```suggestion
`PROOF_GENERATION_ERROR` MUST be raised.
```

2022-10-12 21:05 UTC, TallTed commented on index.html
> +or <var>proofPurpose</var> values are not set in <var>proof</var> a
```suggestion
or <var>proofPurpose</var> values are not set in <var>proof</var>, a
```

2022-10-12 21:05 UTC, TallTed commented on index.html
> +PROOF_GENERATION_ERROR MUST be raised.
```suggestion
<var>options</var> but are not set in <var>proof</var>, a
`PROOF_GENERATION_ERROR` MUST be raised.
```

2022-10-12 21:10 UTC, dlongley approved these changes
Ok, given your explanation for cryptosuites like BBS, @msporny. We might want a note that says that particular cryptosuites might define `hashData` to be a comprised of multiple parts to be processed independently in the proof generation algorithm, it needn't be a single opaque value.

2022-10-16 21:11 UTC, msporny commented
> Ok, given your explanation for cryptosuites like BBS, @msporny. We might want a note that says that particular cryptosuites might define `hashData` to be a comprised of multiple parts to be processed independently in the proof generation algorithm, it needn't be a single opaque value.

Done in 2d1558ee74cfdc1e3b234f1dff0440e9c3e38b25.

2022-10-16 21:12 UTC, msporny commented
Normative, multiple reviews, changes suggested and made, no objections, meging.

2022-10-16 21:12 UTC, merged