Remove the unnecessary Create Verify Hash Algorithm.
w3c/vc-data-integrity pull request #63
Opened 2022-10-16 22:07 UTC by msporny

This PR removes the unnecessary Create Verify Hash Algorithm, which was hard coded to presume digital signatures only. The hashing algorithm is now defined by cryptosuites, which greatly simplifies how much bouncing around is done between the algorithms in the Data Integrity specification and the cryptosuite specifications.

2022-10-17 00:38 UTC, dlongley commented
Hmm, is there a way we can keep this function so it can be reused by cryptosuites? It will be commonly reused and it would be a shame if every cryptosuite had to redefine it to cross link to some other cryptosuite that it would otherwise not depend on.

2022-10-17 01:57 UTC, msporny commented
> Hmm, is there a way we can keep this function so it can be reused by cryptosuites? It will be commonly reused and it would be a shame if every cryptosuite had to redefine it or cross link to some other cryptosuite that it would otherwise not depend on.

Every cryptosuite is going to have to define the `generate hash algorithm` anyway. It turns out the majority of this text was easily absorbed into the `generate proof` and `verify proof` text... making this text redundant. 

What parts of the algorithm do you think we're going to need to keep?

2022-10-17 15:43 UTC, TallTed requested changes
A couple of words...

2022-10-17 15:43 UTC, TallTed commented on index.html
> +<a href="#dfn-hashing">hashing</a> <var>transformedDocument</var>
```suggestion
<a href="#dfn-hashing">hashing</a> the <var>transformedDocument</var>
```

2022-10-17 15:43 UTC, TallTed commented on index.html
> +advised that particular cryptographic suites might define `hashData` to be a
```suggestion
advised that some cryptographic suite(s) might define `hashData` to be
```

2022-10-17 16:48 UTC, OR13 approved these changes

2022-10-19 02:52 UTC, TallTed approved these changes

2022-10-19 14:41 UTC, dlongley approved these changes
Thanks! We don't need to hold this up based on the concern I raised, we'll figure out the right way to deal with it as we move forward.

2022-10-19 15:15 UTC, mprorock approved these changes

2022-10-19 15:16 UTC, sbutterfield approved these changes

2022-10-19 16:10 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-10-19-vcwg#section2-2) on 2022-10-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.2. Remove the unnecessary Create Verify Hash Algorithm. (pr vc-data-integrity#63)

_See github pull request [vc-data-integrity#63](https://github.com/w3c/vc-data-integrity/pull/63)._




**Manu Sporny:** still trying to figure out what the text might be for this.  
… we will remove the current wrong language.  
… key thing is that the way verify hash is created in BBS will be different to all other crypto suites.  
… its hard to predict what will happen with BBS so getting the language right now will be difficult.  

**Markus Sabadello:** might fit into RCH working group.  

**Manu Sporny:** we will remove the wrong text now. Worst case is that every crypto algorithm might have to use same text.  

</details>

2022-10-23 20:15 UTC, msporny commented
@dlongley wrote:
> is there a way we can keep this function so it can be reused by cryptosuites

I added an issue marker in 33e83ae2f639e64a1a7d1301ffaed6b9fac5a90a to track that we might define this later based on how cryptographic suite specification authoring goes.

2022-10-23 20:16 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2022-10-23 20:16 UTC, merged